#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Mabasic\Maria\Commands\Fit;

$app = new Application("Maria", "0.1.0");

$app->add(new Fit);

$app->run();
